pipeline {
    agent { label 'agent' }

    triggers {
        githubPush() 
    }

    tools {
        jdk 'jdk21'
        nodejs 'node21'
    }

    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
        BACKEND_IMAGE = "daer174/wanderlust-backend"
        FRONTEND_IMAGE = "daer174/wanderlust-frontend"
    }

    stages {
        stage('SCM Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/nggiabao/devops-project.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('wanderlust-web-app/backend') {
                    sh "npm install || true"
                }
                dir('wanderlust-web-app/frontend') {
                    sh "npm install"
                }
            }
        }

        stage('Run SonarQube') {
            environment {
                scannerHome = tool 'sonar-scanner'
            }
            steps {
                withSonarQubeEnv('sonar-server') {
                    sh """
                        ${scannerHome}/bin/sonar-scanner \
                        -Dsonar.projectKey=blog-app \
                        -Dsonar.projectName=blog-app \
                        -Dsonar.sources=wanderlust-web-app
                    """
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('wanderlust-web-app') {
                    sh '''
                        docker build -t ${BACKEND_IMAGE}:${IMAGE_TAG} ./backend
                        docker build -t ${FRONTEND_IMAGE}:${IMAGE_TAG} ./frontend
                    '''
                }
            }
        }

        stage('Scan with Trivy') {
            steps {
                script {
                    def trivyDir = "${WORKSPACE}/trivy-reports"

                    def images = [
                        [name: "${BACKEND_IMAGE}:${IMAGE_TAG}", output: "trivy-backend.txt"],
                        [name: "${FRONTEND_IMAGE}:${IMAGE_TAG}", output: "trivy-frontend.txt"]
                    ]

                    for (img in images) {
                        echo "🔍 Scanning ${img.name}..."
                        sh """
                            docker run --rm \
                                -v /var/run/docker.sock:/var/run/docker.sock \
                                -v \$HOME/.trivy-cache:/root/.cache/ \
                                -v ${trivyDir}:/reports \
                                aquasec/trivy image \
                                --scanners vuln \
                                --severity HIGH,CRITICAL \
                                --timeout 15m \
                                --exit-code 0 \
                                --format table \
                                ${img.name} > ${trivyDir}//${img.output}
                        """
                    }
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([string(credentialsId: 'docker-hub-token', variable: 'DOCKER_TOKEN')]) {
                    sh '''
                        echo "${DOCKER_TOKEN}" | docker login -u daer174 --password-stdin
                        docker push ${BACKEND_IMAGE}:${IMAGE_TAG}
                        docker push ${FRONTEND_IMAGE}:${IMAGE_TAG}
                    '''
                }
            }
        }

        stage('Remote Deploy on Host with Docker Compose') {
            steps {
                sshagent(credentials: ['deploy-server-ssh']) {
                    sh '''
                        echo "🚀 Deploying on host with docker compose..."
                        ssh -o StrictHostKeyChecking=no user@192.168.1.129 '
                            cd /home/user/devops-project/wanderlust-web-app &&
                            docker compose pull &&
                            docker compose up -d
                        '
                    '''
                }
            }
        }
    } 
    post {
        always {
            // Updated to archive all Trivy reports
            archiveArtifacts artifacts: 'trivy-reports/**', fingerprint: true
        }
    }
}
